-- Bookstore Platform v2 — Part 13 ch.06: the outbox table DDL. The orders-
-- service writes (order_row, outbox_row) in ONE transaction; the outbox-
-- publisher Deployment reads ready rows and ships them to Kafka.
--
-- This is the "transactional outbox" pattern (Debezium calls it the "outbox
-- pattern"; same shape). The atomicity guarantee comes from Postgres — both
-- inserts are in the same transaction, both commit or neither does — and
-- avoids 2PC across the application + Kafka.
--
-- Applied via CNPG migration job, or by the Crossplane BookstoreTenant
-- Composition stamping a per-tenant logical DB with this DDL in its
-- initdb script. The chapter sketches both.
--
-- Idempotency: the publisher reads rows where published_at IS NULL,
-- publishes to Kafka with `event_id` as the Kafka message key (so per-
-- partition order is preserved), then UPDATEs published_at. Crashes
-- between publish + UPDATE result in a duplicate publish; consumers
-- dedupe on `event_id`.

CREATE SCHEMA IF NOT EXISTS bookstore_platform;

CREATE TABLE IF NOT EXISTS bookstore_platform.outbox (
    -- A UUID generated by the orders-service at insert time; carried as
    -- the Kafka message key so consumers can dedupe.
    event_id      uuid        NOT NULL PRIMARY KEY,
    -- The business aggregate the event belongs to ("orders").
    aggregate     text        NOT NULL,
    -- The aggregate's row id ("orders.id").
    aggregate_id  text        NOT NULL,
    -- The event type ("OrderPlaced", "OrderCancelled").
    event_type    text        NOT NULL,
    -- The full event payload as JSON. Schema versioning lives inside the
    -- payload (`payload.schema_version`).
    payload       jsonb       NOT NULL,
    -- Tenant scope; the publisher uses this for per-tenant Kafka routing
    -- (or per-tenant topic naming, depending on ops scale).
    tenant_id     text        NOT NULL,
    -- When the row was written by the orders-service.
    created_at    timestamptz NOT NULL DEFAULT now(),
    -- When the publisher acknowledged the Kafka publish. NULL = not yet
    -- published; the publisher's index scan filters on this.
    published_at  timestamptz NULL
);

-- Index supporting the publisher's "find unpublished" scan. A partial
-- index on `published_at IS NULL` keeps the index small even after years
-- of history (published rows are excluded from the index).
CREATE INDEX IF NOT EXISTS outbox_unpublished_idx
    ON bookstore_platform.outbox (created_at)
    WHERE published_at IS NULL;

-- Retention: in production a cron job archives rows older than 30 days to
-- cold storage and deletes them here. The chapter calls out the
-- alternative: never delete (audit-grade event log) — pick based on the
-- regulatory regime.
