apiVersion: v1
kind: Service
metadata:
  name: recommendations
  namespace: bookstore-platform-acme-books
  labels:
    app: recommendations
    app.kubernetes.io/part-of: bookstore-platform
    app.kubernetes.io/component: recommendations-api
    bookstore-platform.example.com/tenant: acme-books
spec:
  selector:
    app: recommendations
  ports:
    - name: http
      port: 8080
      targetPort: 8080
