//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.
//
// Committed equivalent of `make generate` output so the module builds without
// controller-gen installed. Regenerate with `make generate` after editing
// *_types.go.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BookstoreTenant) DeepCopyInto(out *BookstoreTenant) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new BookstoreTenant.
func (in *BookstoreTenant) DeepCopy() *BookstoreTenant {
	if in == nil {
		return nil
	}
	out := new(BookstoreTenant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is a deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BookstoreTenant) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BookstoreTenantList) DeepCopyInto(out *BookstoreTenantList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BookstoreTenant, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new BookstoreTenantList.
func (in *BookstoreTenantList) DeepCopy() *BookstoreTenantList {
	if in == nil {
		return nil
	}
	out := new(BookstoreTenantList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is a deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BookstoreTenantList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BookstoreTenantSpec) DeepCopyInto(out *BookstoreTenantSpec) {
	*out = *in
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new BookstoreTenantSpec.
func (in *BookstoreTenantSpec) DeepCopy() *BookstoreTenantSpec {
	if in == nil {
		return nil
	}
	out := new(BookstoreTenantSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BookstoreTenantStatus) DeepCopyInto(out *BookstoreTenantStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new BookstoreTenantStatus.
func (in *BookstoreTenantStatus) DeepCopy() *BookstoreTenantStatus {
	if in == nil {
		return nil
	}
	out := new(BookstoreTenantStatus)
	in.DeepCopyInto(out)
	return out
}
