apiVersion: v1
kind: Service
metadata:
  name: events-drift-relay
  namespace: bookstore-platform-ml
  labels:
    app: events-drift-relay
    app.kubernetes.io/part-of: bookstore-platform
    app.kubernetes.io/component: drift-relay
spec:
  selector:
    app: events-drift-relay
  ports:
    - name: http
      port: 8080
      targetPort: 8080
