apiVersion: v1
kind: Service
metadata:
  name: catalog
  namespace: bookstore-platform-catalog
  labels:
    app: catalog
    app.kubernetes.io/name: catalog
    app.kubernetes.io/part-of: bookstore-platform
    app.kubernetes.io/component: catalog
spec:
  selector:
    app: catalog
  ports:
    - name: http
      port: 8080
      targetPort: 8080
